### ISSUE TITLE
Allatori-crack-6.0 ClassNameGen

### ISSUE THREAD

**Issue by alexandrage** [MoofMonkey/Allatori-crack-6.0#1]
The names are not the same when calling methods

**Comment by MoofMonkey** [comment]
Okay

**Comment by MoofMonkey** [comment]
Alexandrage, Я отлично знаю что ты русский. Если можешь - сделай Pull Request - мало времени.
----
Alexandrage, I know that you're russian. If you can - make Pull Request - i have too little time.

**Comment by alexandrage** [comment]
Забей, я уже получил не коммерческую лицензию.
