### ISSUE TITLE
ALLATORIxDEMO

### ISSUE THREAD

**Issue by wangiswang** [MoofMonkey/Allatori-crack-6.0#2]
i have cracked allatori 6.0  and it works .
but i find there still exists ALLATORIxDEMO field in obf-xxxxxx.jar file
what is wrong ?  is it I'm not dealing with it ?
Hope to receive reply.   thx

**Comment by MoofMonkey** [comment]
Just... [Go to line 108](https://github.com/MoofMonkey/Allatori-crack-6.0/blob/master/net/moofMonkey/eye/modules/ClassTransformer.java)
And analyze allatori code. Analyze "by eyes" is really difficult task.
P.S.: settings in luyten:

> Show synthetic members - ON
> Bytecode OST/Bytecode - Select that more convenient for you.

And go crack.. Allatori 6.0 haven't many differences with Allatori 5.8. If you don't have time to crack 6.0 - just use my crack for 5.8, or crack for 6.0, but fix issue #1.

**Comment by Eyremba** [comment]
Why are you even so stupid that you try to crack it? Can you even read? You can clearly find this here on the page of Allatori: "Educational and non-commercial project developers may be eligible to receive Allatori Obfuscator for free. Contact our Sales Department to find out." So my friend just wrote an email to them and explained that he is a student, and het got instantly the full version for free without limitations. So why even cracking it when you can just write an email in one minute?!
